import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { AppHeader } from "@/components/app-header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontGeist = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-sans",
});

const fontGeistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontGeist.variable} ${fontGeistMono.variable}`}
      suppressHydrationWarning
    >
      <body>
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full">
              <AppHeader />
              <div>{children}</div>
            </main>
            <Toaster position="bottom-right" closeButton richColors />
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";
